import Vue from 'vue'
import Router from 'vue-router'
import Layout from '@/views/layout/layout.vue'
import Home from './views/vue-cli/home.vue'

Vue.use(Router)

export default new Router({
  mode: 'history',
  base: process.env.BASE_URL,
  routes: [
    // code-gen
    {
      path: '/code-gen',
      name: 'CodeGenerator',
      meta: { title: '代码生成器', icon: 'code' },
      component: Layout,
      children: [{
        path: 'entity',
        name: 'EntityGenerator',
        meta: { title: '实体生成器', icon: 'entity' },
        component: () => import('@/views/code-gen/entity.vue')
      }]
    },

    // system
    {
      path: '/system',
      name: 'System',
      meta: { title: '系统设置', icon: 'system' },
      component: Layout,
      children: [{
        path: 'connection',
        name: 'ConnectionManagement',
        meta: { title: '数据库连接', icon: 'connection' },
        component: () => import('@/views/system/connection.vue')
      }]
    },

    // generated by vue-cli
    {
      path: '/vue-cli',
      name: 'VueCli',
      redirect: '/vue-cli/home',
      meta: { title: 'Vue-cli Generated', icon: 'vue', hidden: true },
      component: Layout,
      children: [
        {
          path: 'home',
          name: 'Home',
          meta: { title: 'Home', icon: 'home' },
          component: Home
        },
        {
          path: 'about',
          name: 'About',
          // route level code-splitting
          // this generates a separate chunk (about.[hash].js) for this route
          // which is lazy-loaded when the route is visited.
          meta: { title: 'About', icon: 'about' },
          component: () => import(/* webpackChunkName: "about" */ './views/vue-cli/about.vue')
        }
      ]
    },

    { path: '/', redirect: '/code-gen/entity', meta: { hidden: true } },
    { path: '/404', component: () => import('@/views/404.vue'), meta: { hidden: true } },
  ]
})
